export const agencyConsignees = [
  {
    id: 1,
    day: "LUNES",
    product: "FRUTA",
    agencyName: "NAVECUADOR",
    agencyId: "24b12203-5b19-4a55-ba54-230f9bc4e7ab",
    consigneeName: "Consignatario 1",
    consigneeId: "2c3c3895-4f17-43d8-9c4e-51adb2cc08ee",
    edit: {
      tag: "",
      valueKg: 10,
      valueMt: 0,
    },
    close: {
      tag: "",
      valueKg: 1.4,
      valueMt: 0,
    },
    booking: {
      tag: "",
      valueKg: 7.6,
      valueMt: 0,
    },
    structural: {
      tag: "",
      valueKg: 80,
      valueMt: 0,
    },
  },
  {
    id: 2,
    day: "LUNES",
    product: "FRUTA",
    agencyName: "NAVECUADOR",
    agencyId: "24b12203-5b19-4a55-ba54-230f9bc4e7ab",
    consigneeName: "Consignatario 2",
    consigneeId: "1d4d4906-4f17-43d8-9c4e-51adb2cc08ee",
    edit: {
      tag: "",
      valueKg: 50,
      valueMt: 0,
    },
    close: {
      tag: "",
      valueKg: 60,
      valueMt: 0,
    },
    booking: {
      tag: "",
      valueKg: 30,
      valueMt: 0,
    },

    structural: {
      tag: "",
      valueKg: 20,
      valueMt: 0,
    },
  },
  {
    id: 3,
    day: "LUNES",
    product: "FRUTA 2",
    agencyName: "LATAM",
    agencyId: "53G12509-5b19-4a55-ba54-230f9bc4e7ab",
    consigneeName: "Consignatario 2",
    consigneeId: "1d4d4906-4f17-43d8-9c4e-51adb2cc08ee",
    edit: {
      tag: "",
      valueKg: 6.99,
      valueMt: 0,
    },
    close: {
      tag: "",
      valueKg: 1.99,
      valueMt: 0,
    },
    booking: {
      tag: "",
      valueKg: 7,
      valueMt: 0,
    },

    structural: {
      tag: "",
      valueKg: 10,
      valueMt: 0,
    },
  },
  {
    id: 4,
    day: "MARTES",
    product: "FRUTA",
    agencyName: "LATAM",
    agencyId: "53G12509-5b19-4a55-ba54-230f9bc4e7ab",
    consigneeName: "Consignatario 2",
    consigneeId: "1d4d4906-4f17-43d8-9c4e-51adb2cc08ee",
    edit: {
      tag: "",
      valueKg: 6.99,
      valueMt: 0,
    },
    close: {
      tag: "",
      valueKg: 1.99,
      valueMt: 0,
    },
    booking: {
      tag: "",
      valueKg: 7,
      valueMt: 0,
    },
    structural: {
      tag: "",
      valueKg: 10,
      valueMt: 0,
    },
  },
  {
    id: 5,
    day: "MARTES",
    product: "FRUTA",
    agencyName: "LATAM",
    agencyId: "53G12509-5b19-4a55-ba54-230f9bc4e7ab",
    consigneeName: "Consignatario 1",
    consigneeId: "2c3c3895-4f17-43d8-9c4e-51adb2cc08ee",
    edit: {
      tag: "",
      valueKg: 6.99,
      valueMt: 0,
    },
    close: {
      tag: "",
      valueKg: 1.99,
      valueMt: 0,
    },
    booking: {
      tag: "",
      valueKg: 7,
      valueMt: 0,
    },

    structural: {
      tag: "",
      valueKg: 10,
      valueMt: 0,
    },
  },
  {
    id: 6,
    day: "MARTES",
    product: "FRUTA 2",
    agencyName: "NAVECUADOR",
    agencyId: "24b12203-5b19-4a55-ba54-230f9bc4e7ab",
    consigneeName: "Consignatario 1",
    consigneeId: "2c3c3895-4f17-43d8-9c4e-51adb2cc08ee",
    edit: {
      tag: "",
      valueKg: 10,
      valueMt: 0,
    },
    close: {
      tag: "",
      valueKg: 1.4,
      valueMt: 0,
    },
    booking: {
      tag: "",
      valueKg: 7.6,
      valueMt: 0,
    },
    structural: {
      tag: "",
      valueKg: 80,
      valueMt: 0,
    },
  },
  {
    id: 7,
    day: "MARTES",
    product: "FRUTA 2",
    agencyName: "EC TEST",
    agencyId: "12345-5b19-4a55-ba54-230f9bc4e7ab",
    consigneeName: "",
    consigneeId: "",
    edit: {
      tag: "",
      valueKg: 10,
      valueMt: 0,
    },
    close: {
      tag: "",
      valueKg: 1.4,
      valueMt: 0,
    },
    booking: {
      tag: "",
      valueKg: 7.6,
      valueMt: 0,
    },
    structural: {
      tag: "",
      valueKg: 80,
      valueMt: 0,
    },
  },
];
